eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#  instance:
#    hostname: instanceName
server:
  port: 8081
spring:
  application:
    name: customer
env:
  pro8
